export default {
  ocorrencia: 'Tipo de Ocorrência',
  entrada: 'Data de Entrada',
  vencimento: 'Data de Vencimento',
  valor: 'Valor',
  informante: 'Informante',
  contrato: 'Número de Contrato',
  avalista: 'Avalista',
  cidade: 'Cidade',
  uf: 'UF',
  situacao: 'Situação',
  orgaoemissor: 'Orgão Emissor',
  totalpendencias: 'Total de Pendências',
  totalcredores: 'Total de Credores',
  totalvalor: 'Valor Total',
  categoria: 'Categoria',
};
